module.exports=function(questions){
 const extra=[
 ['Q14','Which parts of the framework generalize beyond personhood?','WG-10 · general DTG scope','Our spec covers membership, relationships, attributes, control, status and authority for people, organizations, devices and agents. Personhood and liveness apply only when a use case requires them.','The current draft now states this broader scope; its scope decision is proposed, not recorded as group adoption.','The paper abstract describes PHCs, VRCs and personhood functionalities. This question asks which dependencies can be generalized; no theorem transfer is presumed.','Which definitions and security results survive if a personhood credential is replaced by a general membership or authorization credential? Which uniqueness, enrollment or issuer assumptions must remain?','A boundary between reusable cryptographic machinery and personhood-specific assumptions, with the exact definitions to cite.','Organize the book by graph outcomes and state when personhood is actually required.'],
 ['Q15','What security argument is needed for the composed presentation?','003 / 010 · WG-02 / WG-03','A proof of membership, a relationship proof and a holder-control proof must refer to the same authenticated entities and request.','The records describe a conjunction; separate passing component tests do not establish secure composition or witness consistency.','Ask the authors to name the exact functionality, construction and theorem supporting the composition, including any departures required for DTG credentials.','Should we use one joint proof or linked proofs? What binds shared witnesses, prevents proof splicing and supports concurrent sessions? Which adversaries, issuer collusions, corruptions and setup assumptions does the argument cover?','A composition contract and named proof-system properties, plus a list of statements the DTG extension still needs to justify.','Explain why individual proof validity is insufficient to justify a composed graph claim.'],
 ['Q16','How should the spec express attributes and graph predicates without overclaiming trust?','General outcomes · attribute predicates · future profiles','The broader spec may need hidden attribute checks and bounded relationship/path predicates, with explicit credential authenticity.','No complete attribute or general path profile is supplied by the current records. Reachability is not automatically authorization or trust transitivity.','Extension question for the framework’s predicate interface; request exact applicability rather than assuming arbitrary predicates inherit its security or performance.','Which attribute or bounded graph predicates fit the existing construction interface? What constraints prevent proving a path from being interpreted as delegated authority, independent endorsement or a trust score?','One useful next predicate with an exact statement, disclosure, input requirements and non-goals.','Separate graph structure, policy interpretation and issuer assurance in worked chapters.'],
 ['Q17','What changes under key rotation, recovery or later compromise?','004 / 006 / 007 / 010 · horizon and custody','Long-lived relationships must coexist with key changes, revocation and private presentations.','Existing profiles do not establish a complete recovery strategy or retrospective privacy guarantee for the full construction.','Ask which corruption model and time horizon the paper analyzes; do not infer forward privacy from ordinary zero knowledge.','Can a recovered or rotated holder still use issued credentials and linkage artifacts? Does later compromise of a holder, issuer or prover reveal or link old presentations? What must be reissued, updated or invalidated?','An explicit lifecycle/compromise model and the required update or reissuance artifacts.','Explain which properties survive rotation and which expire with a key, witness or root.'],
 ['Q18','Which transcript encoding and validation profile should we implement?','WG-06 / WG-06a · V02 / V06 · record 003','The authenticated request, external digest and circuit scalar must describe the same statement.','The lab hashes length-prefixed domain and canonical JSON bytes, then reduces SHA-256 modulo the BN254 scalar prime. Plain SHA-256 of the JSON differs. Its validator accepts a numeric challenge and object expiry; stricter checks are now proposed in the spec.','Implementation question: request review of domain separation, tag semantics and field conversion without claiming the paper mandates this lab encoding.','Should we retain this exact framed hash as the first named profile? What external digest encoding, canonicalization constraints and scalar conversion are appropriate? Which checks belong in the circuit versus the authenticated verifier boundary?','A versioned encoding decision, typed payload contract and cross-language negative vectors.','Show the complete bytes-to-digest-to-scalar pipeline and a failing mismatch example.'],
 ['Q19','What is the minimum real credential and task exchange to demonstrate?','WG-04 / WG-07 · V04 / V05 / V11','A proof result should feed an actual trust-graph policy decision while execution and receipts remain distinct.','Trust Tasks/OpenVTC integration is a target, not demonstrated interoperability. A local callback or report checker does not establish a working service exchange.','Ask the authors about the necessary cryptographic interface; task and service design remains a working-group/implementer decision.','What issuance or presentation API must a reference implementation expose? Can it work with existing issuer signatures and non-exportable keys? Where should the proof terminate so policy checks cannot omit a required cryptographic check?','A minimal issuer-holder-verifier interface and a concrete integration fixture with all simulated parts named.','One end-to-end example from accepted credential to verified statement and policy outcome.'],
 ['Q20','Which paper artifacts can seed a reproducible implementation and chapter?','WG-08 / WG-11 · V01 / V07 / V12','Translate construction research into an implementation and a teachable worked proof.','The current catalogue mixes local component measurements, author-reported benchmarks and unimplemented options. Full-paper section matching still needs confirmation.','Request the exact paper revision, implementation branch/commit, parameters and benchmark workload associated with the relevant construction.','Is there reference code, pseudocode, a test-vector set or a parameter-selection guide we can reuse? What is missing to reproduce the claimed result? Who is willing to review the formal mapping or a draft chapter, and under what reuse terms?','Concrete artifact links, reproducibility prerequisites, gaps and explicitly volunteered review roles.','A chapter whose claims map to the paper and whose example can be run from pinned artifacts.']
 ];
 for(const [id,title,records,statement,evidence,paper,ask,decision,book] of extra)questions.push({id,title,records,statement,evidence,paper,ask,decision,book,section:id==='Q14'?'Framing':'Cross-cutting author questions',priority:'Follow-up',url:'https://eprint.iacr.org/2026/333'});
 const wg={Q01:'WG-01',Q02:'WG-02',Q03:'WG-02',Q04:'WG-03',Q05:'WG-06',Q06:'WG-03',Q07:'WG-10',Q08:'WG-05',Q09:'WG-02',Q10:'WG-04',Q11:'WG-11',Q12:'WG-08',Q13:'WG-09'};
 for(const q of questions){if(wg[q.id])q.records+=' · '+wg[q.id];q.priority=['Q14','Q01','Q02','Q15','Q04','Q18','Q12'].includes(q.id)?'Must ask':'Follow-up';}
 const q13=questions.find(q=>q.id==='Q13');q13.evidence='A proposed maintenance process connects source discussions, implementation evidence and reviewed spec/book changes. Meeting notes capture proposals and attribution; they do not themselves ratify or publish decisions.';
 const q05=questions.find(q=>q.id==='Q05');q05.evidence+=' See Q18 for the concrete hash-framing and strict-validation gap identified in the current implementation review.';
 const q12=questions.find(q=>q.id==='Q12');q12.ask='Should the book organize chapters by trust-graph outcome, with statement, assumptions, paper mapping, construction options and a runnable example? Can the authors identify the most useful first chapter and volunteer review of its formal mapping?';
 const order=['Q14','Q01','Q02','Q03','Q04','Q05','Q06','Q07','Q08','Q09','Q15','Q16','Q17','Q18','Q19','Q20','Q10','Q11','Q12','Q13'];questions.sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));
};
