module.exports=function(questions){
const matches={
Q01:'§6 (pp. 29–30) defines vouchable credentials; §§7.1–7.2 give the proof constructions. These are the paper interfaces to compare with the proposed ADR-001 statement.',
Q02:'§6 Vouch/Verify (pp. 29–30) and §7.2.2–7.2.3 (pp. 40–42) specify the credential-derived vouch and PRF/control proof relations. Matching the DTG offline artifact to those interfaces is the discussion question.',
Q03:'Appendix C (pp. 64–67), not Appendix A, gives the generic conversion from regular credentials to vouchable credentials using verification over all attributes, commitments and SE-NIZK. §§8–9 give the specialized black-box route.',
Q04:'§10, Tables 1–2 (pp. 54–56) compares the implemented black-box construction with a Groth16 baseline. The baseline uses BLS12-381, JubJub Schnorr and Pedersen hashing; it is not the local BN254/Poseidon circuit or a benchmark of arbitrary existing credentials.',
Q05:'§3.5, Definition 5 (p. 17) defines tag-based SE-NIZK. §7.2.1 (p. 40) names the proof systems used by Construction II. A bound public scalar does not by itself demonstrate those properties.',
Q06:'§9.1 (pp. 53–54) separates algebraic VRC verification via Groth–Sahai from PRF, revocation and predicate constraints via commit-and-prove SNARK. §10 measures specific implementations; Flock is a separate candidate, not evaluated in this paper.',
Q07:'§5.3 (pp. 27–28) explains the conflict between full unlinkability and underlying-user distinctness and motivates context-scoped keys. §7.2 (pp. 39–42) derives keys with a PRF. Distinct lab leaves are not automatically the paper’s distinct underlying users.',
Q08:'§5.4 (pp. 28–29) treats revocation as an example predicate, not native ideal-functionality support. Its nullifier is revealed during VRC issuance but hidden during showing; the text explicitly notes issuer tracking through that revealed attribute.',
Q09:'§3.2 (p. 16) supplies commitment preliminaries. The proposed DTG taskContext binder is an application-specific design question, not a directly specified paper wire artifact.',
Q10:'Appendix B.1 (pp. 62–63) discusses AI-agent reputation and delegation as an application. It does not specify the full DTG VDC chain profile, acceptance encoding or task invocation protocol.',
Q11:'§10 (pp. 54–56) describes implementation and benchmarking. Rebuilding that experiment and reviewing its security assumptions are separate from accepting a submitted manifest report.',
Q12:'§§6–9 provide the primitive-to-construction progression; §10 supplies the evaluation; Appendix B gives application narratives. These can anchor a book chapter without making the paper the entire DTG specification.',
Q13:'The paper is research evidence. The task force’s discussion, review and adoption process is a separate governance matter.',
Q14:'§4 (pp. 20–22) models a personhood oracle; §5 defines the personhood functionality. §6 offers a generic vouchable-credential primitive. Appendix B includes agent, maintainer and business-network applications. Generalizing the functionality beyond personhood needs explicit assumptions.',
Q15:'§7.2.2 defines L_PRF, L_VRC and L_ShowVRC; §7.2.4 gives the security proof. §9.1 explains the Groth–Sahai/commit-and-prove split. Ask which exact relations and commitments must remain shared in a DTG composition.',
Q16:'§7.2.2 includes predicate f over attributes, statements, contexts and context keys; §9.1 separates predicate satisfaction from VRC verification. Appendix B motivates graph applications but does not make reachability equivalent to authority.',
Q17:'§§5.1–5.2 define the security interpretation, and §5.4 discusses revocation limitations. Rotation, recovery and retrospective privacy for the DTG profile remain questions to resolve explicitly; no lifecycle theorem is inferred here.',
Q18:'§3.5 defines tagged proof verification, while the exact domain/length framing and field conversion are local DTG implementation choices. The lab profile therefore needs its own encoding and verifier-boundary specification.',
Q19:'§6 defines credential issuance and Vouch/Verify; §7.2.3 defines the proof protocol. Trust Tasks, OpenVTC APIs and execution receipts are DTG integration work beyond these paper interfaces.',
Q20:'§10 (p. 54) identifies the reference implementation: https://github.com/LF-Decentralized-Trust-labs/zkbk. The evaluation uses one CPU core on an Apple M4 Pro with 32 GB RAM and averages 20 runs (p. 55). Request the exact commit and workload to reproduce.'};
for(const q of questions){q.paper=matches[q.id]||q.paper;}
questions.find(q=>q.id==='Q20').ask='The paper links the zkbk reference implementation. Which commit, parameter set and benchmark commands reproduce §§8–10, and what additional work is needed for our first DTG profile? Can you help review the formal mapping and a runnable book chapter?';
questions.push({id:'Q21',section:'Cross-cutting author questions',priority:'Follow-up',title:'What can sampling establish after full signature verification?',records:'Discussion #12 · construction selection · V07',statement:'Keep full credential authenticity separate from the statistical claim made by sampling a content predicate.',evidence:'An existing task-force comment proposes verifying signatures across the full set while sampling expensive predicates. Its performance and confidence claims need a concrete threat model and workload.',paper:'§9.1 (pp. 53–54) explicitly includes predicate satisfaction as well as VRC validity and PRF ownership. §10 measures concrete routes. It would be inaccurate to summarize the whole paper as providing signature validity only.',ask:'Which checks are covered by the full proof and which would be sampled? How is the committed population fixed before unbiased sampling, how are duplicates or selective aborts handled, and what false-accept bound does the result support? Can repeated sampling leak attributes or permit grinding?',decision:'An exact statistical statement, adversarial sampling model and cost comparison. Sampling must not be described as proving every credential satisfies the predicate.',book:'Distinguish universal proof claims from probabilistic evidence and show the assumptions behind the confidence bound.',url:'https://github.com/trustoverip/dtgwg-zkp-tf/discussions/12'});
questions.push({id:'Q22',section:'Cross-cutting author questions',priority:'Follow-up',title:'What setup and parameter governance does each route require?',records:'WG-03 · V01 / V07',statement:'Assess setup, security level and artifact governance for every construction route, including wrappers.',evidence:'The existing call material previously suggested that only the lab route requires a ceremony. The paper’s black-box instantiation also specifies a trusted setup.',paper:'§9.1 (p. 53), “Trusted Setup”, specifies KZG CRS and SPS parameters established before issuer initialization. §10 uses a concrete BLS12-381 instantiation; these choices need to be matched to a DTG profile.',ask:'Which parameters are trusted, reusable, circuit-specific or updatable? What assumptions protect against malicious setup and issuer keys, and what artifacts must implementers pin? Does a transparent backend become setup-dependent through a wrapper?',decision:'A per-route setup and security matrix, with an explicit verification-key/parameter distribution policy.',book:'Explain setup at the construction level, including composition and wrappers, rather than as a single vendor badge.',url:'https://eprint.iacr.org/2026/333'});
};
