const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
module.exports=function(html){
const ds=JSON.parse(html.match(/<script type="application\/json" id="reader-data">([\s\S]*?)<\/script>/)[1]);
const status=require('node:fs').readFileSync('outputs/repository-push-status.html','utf8');
const map=`<section class="ritedef" id="repo-routing"><h2>Today’s repository and publication map</h2><p><b>Local preparation home:</b> dtgwg-zkp-tf-mage/task-force-readers. This is your agent workspace; selected task-force contributions go to the organisation remote. The similarly named dtgwg-zkp-mage is the separate implementation evidence repository.</p><ul><li><b>Task force → trustoverip/dtgwg-zkp-tf:</b> meeting documents, questions, requirements, discussions and recorded decisions. Reader files need their own TF change/PR if shared through Git; they are not part of spec PR P.</li><li><b>ZKP spec → trustoverip/dtgwg-zkp-spec:</b> specification, book, construction records and conformance. P is this repository’s PR; R links to its actual URL.</li><li><b>Credential spec → trustoverip/dtgwg-cred-spec:</b> credential definitions, fields and normative format changes. N is an issue reply here, not a credential-spec PR. A code/text change needs a separate branch and PR in its credential-spec checkout.</li><li><b>Credential TF → trustoverip/dtgwg-cred-tf:</b> cross-task-force discussion, including K in #39. It is distinct from the credential-spec repository.</li><li><b>Implementation evidence → mitchuski/dtgwg-zkp-mage:</b> circuits, experiments, measurements and reproduction. Its legacy local folder name dtgwg-cred-spec-main_mage does not make it the credential specification. Trust Tasks/OpenVTC implementation changes belong to their owning repositories and are linked as evidence.</li></ul><p><b>After commit-and-push preparation:</b> P (required spec PR) → R → K → N → other active follow-ups → T after the call. Held items are reference-only. Before each mutation, verify the target repository and branch, the current remote thread and any prerequisite public links. A Git push, PR creation, discussion post and issue comment are separate actions.</p><p>Read and edit the exact draft, save, review its proverb, then export the revision-bound handoff. Browser edits are not yet repository files. Export before committing them; do not assume a source rebuild includes browser changes.</p></section>`;
html=html.replace('<section class="ritedef" id="publishing-plan">',status+map+'<section class="ritedef" id="publishing-plan">');
// Retain dated planning material, but remove it from the current sequential workflow.
html=html.replace(/(<h2[^>]*id="run"[\s\S]*?)(<h2[^>]*id="watch")/,'<details><summary>Earlier run plan — source snapshot; use the current repository map and queue below</summary>$1</details>$2');
html=html.replace(/(<h2[^>]*id="doors"[\s\S]*?)(<section class="ritedef" id="push-readiness")/,'<details><summary>Earlier opportunity list — source snapshot, refresh before acting</summary>$1</details>$2');
const cards=[];html=html.replace(/<article class="card[^"]*" id="draft-([^" ]+)"[\s\S]*?<\/article>/g,(card,id)=>{const d=ds.find(x=>x.id===id);const u=new URL(d.target);const repo=u.pathname.split('/').slice(1,3).join('/');const kind=u.pathname.includes('/compare/')?'Spec pull request — after branch push':u.pathname.includes('/issues/')?'Issue comment':u.pathname.includes('/pull/')?'Pull-request comment':u.pathname.endsWith('/discussions/new')?'New discussion':'Discussion reply';card=card.replace('<div class="body">','<div class="note"><b>[Agent navigation — not part of the post]</b><br><b>Action:</b> '+kind+' · <b>Destination repository:</b> '+escape(repo)+'<br>Exact target: '+escape(d.target)+'</div><div class="body">');cards.push({id,card,blocked:!!d.blocked});return '<!--CARD:'+id+'-->'});
const order=['P','R','K','N'];cards.sort((a,b)=>{const rank=x=>x.blocked?100:x.id==='T'?90:order.includes(x.id)?order.indexOf(x.id):10;return rank(a)-rank(b)});
let placed=false;html=html.replace(/<!--CARD:[^>]+-->/g,()=>{if(placed)return '';placed=true;return cards.map(c=>c.card).join('\n')});
return html;
};
